.env.example, README.md, docker-compose.yml, gulpfile.babel.js
Hi, 
I added a Redis a Mongo service to the docker-composer file. I also added proper configuration to the RESTFul API service in order to work with docker services. Let me know if you have any questions.
=> Added Docker Support for development environment

server/controllers/favorite.controller.js, server/controllers/post.controller.js, server/models/favorite.model.js, server/models/post.model.js, server/models/vote.model.js, server/routes/favorite.route.js, server/routes/index.route.js, server/routes/post.route.js, server/tests/favorite.test.js, server/tests/post.test.js
Implement the route to favorite and unfavorite a post.
=> Fixes #4: Create route for favorites

package.json
=> Update istanbul to 1.0.0-alpha.2

server/controllers/listened.controller.js, server/middleware/isOwnUser.js, server/models/listened.model.js, server/routes/index.route.js, server/routes/listened.route.js, server/routes/post.route.js, server/tests/listened.test.js
Created the model, controller, and routes for #5. Unit tests we also added so feel free to run those.  
Routes: 
GET /api/posts/{postId}/listened
- Returns a list of users that listened to the post
- No auth required
POST /api/posts/{postId}/listened
- Marks the post as listened by a user
- Auth required
GET /api/listened
- Returns a list of posts a user has listened to
Let me know if you have any questions.
=> Mark post as listened

.travis.yml, package-lock.json, package.json
Fixes https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/issues/17
=> Travis fix

server/controllers/comment.controller.js, server/models/comment.model.js, server/routes/post.route.js, server/tests/comment.test.js
Still needed but not part of this PR:
[ ] delete / update
[ ] pagination 
[ ] figure out how we will implement Usernames+Real Names so we can launch to prod
Tests:
[ ] need to check that when no content field is provided it throws back an error
=> Comments v1

server/models/post.model.js
I believe the docs had just been copied from the User model and hence had faulty docs and comments. Just corrected it. @TheHollidayInn @jasonify
=> Correct post model doc

README.md
Add SEDaily icon, build status, and links to the API clients
=> Add flair to the README.md

docker-compose.yml
I think this is what was wanted from this issue. Also not entirely sure if a container name is required or if the ordering of the containers matter. 
#61
=> Remove duplicate mongo services in docker-compose.yml

server/controllers/user.controller.js, server/routes/user.route.js
RE: https://github.com/SoftwareEngineeringDaily/software-engineering-daily-api/issues/70
This is only a quick fix to not expose those two fields but I do think we need a better solution going forward. :)
@crablar 
@joshmorel
=> Remove password + email from response to get user.

README.md
=> Add info on installing deps with docker

server/controllers/feed.controller.js, server/models/feed.model.js, server/routes/feed.route.js
=> modified feed controller to return Jeff's feed when logged out

server/models/favorite.model.js, server/tests/favorite.test.js
@justinctlam This will resolve #121 
Thank you for your patience on this.
=> exclude active=false bookmarks in user/:userId/bookmarked

config/config.js, config/param-validation.js, package.json, server/controllers/user.controller.js, server/models/PasswordReset.model.js, server/models/comment.model.js, server/models/resetPassword.model.js, server/models/user.model.js, server/routes/user.route.js
Mostly checking if Travis is working..
=> WIP: Feature/reset password

.env.docker_example, .env.local_example
=> added SEND_GRID_KEY to env examples

server/tests/comment.test.js
Fixes #80 
I wrote the tests to check whether upvote comments and replies work.
Not sure how you guys wanted to tackle those tests but here comes the first attempt. 
While working on that, I might have solved #79 as well, but you tell me :)
=> Test upvote comments and replies

.eslintrc
=> added MemberExpression to indent rules

server/controllers/auth.controller.js, server/controllers/comment.controller.js, server/controllers/job.controller.js, server/models/comment.model.js, server/tests/comment.test.js
Deleted Comments now return "Deleted on <date>" when fetched. #174
=> implemented issue #174

index.js
=> fix mongoose deprecation warning

server/models/relatedLink.model.js, server/tests/relatedLink.test.js
=> Fix related links if unauth and add test coverage

.env.local_example, .gitignore, .travis.yml, config/config.js, devops/.env.ci, devops/build-api.sh, devops/build-mongodb.sh, devops/ci.Dockerfile, devops/mongo.Dockerfile, devops/mongo.sh, docker-compose.yml, package.json, server/controllers/auth.controller.js, server/middleware/validateRecaptcha.middleware.js, server/package-lock.json, server/routes/auth.route.js, server/routes/forum.route.js
* Automate building Docker images of the API and MongoDB
=> Deploy Travis CI automation, add recaptcha

package-lock.json, package.json, server/controllers/post.controller.js, server/models/post.model.js, server/routes/post.route.js
Adds an endpoint for handling post search and pagination.
=> feat(algolia): add search endpoint

server/controllers/user.controller.js, server/routes/user.route.js, server/tests/user.test.js
Added new users route `/api/users/search/names` to return just the users names.
=> New user route added for comment tags

server/controllers/relatedLink.controller.js, server/models/relatedLink.model.js
Added an episode type to user submitted links
=> feat(): add episode type

config/param-validation.js, config/websocket.js, server/controllers/auth.controller.js, server/controllers/comment.controller.js, server/controllers/profile.controller.js, server/controllers/user.controller.js, server/controllers/vote.controller.js, server/tests/auth.test.js
Changes that remove username access to the user
=> Removed username references

server/controllers/profile.controller.js
Fixes https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/679
=> fix(): profile path

server/controllers/topic.controller.js, server/helpers/mail.js, server/routes/topics.route.js, server/templates/email/sd-body-topic-interest.handlebars
=> Added Write topic interest routes

server/controllers/user.controller.js
[Issue](https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/647)
=> Refresh browser profile pic on update

package-lock.json, package.json, server/controllers/user.controller.js, server/helpers/searchParser.helper.js
Based in [qs-mongodb](https://www.npmjs.com/package/qs-mongodb)
=> Added querystring search mongodb engine

server/models/post.model.js
For https://github.com/SoftwareEngineeringDaily/sedaily-front-end/pull/733
=> Added slug to post standardSelectForFind

server/controllers/answer.controller.js, server/controllers/question.controller.js, server/controllers/topic.controller.js, server/controllers/topicPage.controller.js, server/models/answer.model.js, server/models/question.model.js, server/routes/answer.route.js, server/routes/index.route.js, server/routes/question.route.js, server/routes/topicPage.route.js
Fixes https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/750
=> feat(qa): #750 qa routes

server/controllers/profile.controller.js, server/controllers/question.controller.js, server/controllers/topicPage.controller.js, server/helpers/activity.helper.js, server/helpers/badge.helper.js, server/models/answer.model.js
Supports fixes in:
- https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/756
- https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/757
=> feat profile topics

server/controllers/user.controller.js, server/middleware/ensureIsSuperAdmin.middleware.js, server/routes/user.route.js
Routes and changes for User Admin
=> New User Admin panel

server/controllers/topic.controller.js, server/routes/topic.route.js
Fix topic related episodes from tags to topics
Create Related Episode in topic
=> Create Related Episode in topic

server/controllers/post.controller.js, server/controllers/question.controller.js, server/controllers/topicPage.controller.js, server/middleware/response.middleware.js, server/routes/post.route.js
Fixes:
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/762
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/767
=> feat(): populate posts with related questions, sort questions by answer

config/param-validation.js, server/controllers/comment.controller.js, server/models/comment.model.js, server/routes/comment.route.js
Fixes
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/770
=> feat(): support optional content when creating highlight

migrations/1588964716270-multiple-topic-maintainers.js, migrations/1589311757761-index-topics.js, server/controllers/answer.controller.js, server/controllers/topic.controller.js, server/controllers/topicPage.controller.js, server/models/topicPage.model.js
Supports:
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/699
=> feat(): support indexing topics, answers, on update, migration

server/controllers/question.controller.js, server/controllers/topic.controller.js, server/routes/question.route.js
Supports:
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/797
=> feat(): add unanswered questions endpoint #797

server/controllers/question.controller.js, server/controllers/topic.controller.js, server/helpers/mail.js, server/templates/email/sd-body-topic-new-question.handlebars
Supports:
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/821
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/835
=> feat(): add new question email, push notification #821

package-lock.json, package.json, server/controllers/topicPage.controller.js, server/controllers/twitter.controller.js, server/models/topicPage.model.js, server/routes/index.route.js, server/routes/twitter.route.js
Supports:
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/851
=> feat(): add twitter accounts to topicPages, twitter search

server/controllers/topic.controller.js, server/routes/topics.route.js
Supports:
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/849
=> feat(): add remove maintainer endpoint #849

server/controllers/auth.controller.js, server/models/passport.model.js, server/routes/auth.route.js
Supports: 
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/861
=> feat(): add twitter oauth endpoint #861

server/controllers/post.controller.js, server/routes/post.route.js
Supports:
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/872
=> feat(): add popular posts endpoint

server/controllers/question.controller.js, server/models/question.model.js, server/routes/question.route.js
Supports:
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/800
=> feat(): add question ordering endpoint

server/controllers/auth.controller.js, server/controllers/profile.controller.js
Supports changes to:
https://softwaredaily.slack.com/archives/DFVF7KFB6/p1591972875004100
=> feat(): remove badges from profile request, add twitter username to signup

server/controllers/topic.controller.js, server/controllers/topicPage.controller.js, server/models/user.model.js
Supports:
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/880
=> feat(): add twitter, sortby date to topicpage maintainers

server/crons/rssFeed.cron.js
Fixes:
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/892
=> fix(): rss podcast description with cleaned up content - fixes #892

server/crons/rssFeed.cron.js, server/models/post.model.js
Fixes #892
https://github.com/SoftwareEngineeringDaily/sedaily-front-end/issues/892
=> fix(): rss podcast description

package-lock.json
- Updated package-lock.json file
=> fix: Updated package-lock.json file
